// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using investAPI.Data;

#nullable disable

namespace investAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220804192015_Base-inicial")]
    partial class Baseinicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("investAPI.Models.Reit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("averagePrice")
                        .HasColumnType("REAL");

                    b.Property<float>("currentQuote")
                        .HasColumnType("REAL");

                    b.Property<float>("profit")
                        .HasColumnType("REAL");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("total")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Reits");

                    b.HasData(
                        new
                        {
                            id = 1,
                            averagePrice = 10f,
                            currentQuote = 15f,
                            profit = 10f,
                            quantity = 2,
                            ticker = "MXRF11",
                            total = 20f
                        },
                        new
                        {
                            id = 2,
                            averagePrice = 10f,
                            currentQuote = 15f,
                            profit = 10f,
                            quantity = 2,
                            ticker = "HGLG11",
                            total = 20f
                        });
                });

            modelBuilder.Entity("investAPI.Models.Stock", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("averagePrice")
                        .HasColumnType("REAL");

                    b.Property<float>("currentQuote")
                        .HasColumnType("REAL");

                    b.Property<float>("profit")
                        .HasColumnType("REAL");

                    b.Property<int>("quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ticker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("total")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            id = 1,
                            averagePrice = 10f,
                            currentQuote = 15f,
                            profit = 10f,
                            quantity = 2,
                            ticker = "CEMIG3",
                            total = 20f
                        },
                        new
                        {
                            id = 2,
                            averagePrice = 10f,
                            currentQuote = 15f,
                            profit = 10f,
                            quantity = 2,
                            ticker = "WEG3",
                            total = 20f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
